#########################
## Sample Sass Lint File
#########################
# Linter Options
options:
  formatter: stylish
files:
  include:
    - 'pages/**/*.scss'
    - 'components/**/*.scss'
# Don't merge default rules
merge-default-rules: false
# Set the formatter to 'html'
# Output file instead of logging results
# Raise an error if more than 50 warnings are generated
max-warnings: 50

rules:
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 2
  no-color-literals: 0
  no-combinators: 0
  no-css-comments: 0
  no-debug: 2
  property-sort-order: 0
  no-disallowed-properties: 0
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements: 2
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 2
  no-universal-selectors: 0
  no-url-domains: 0
  no-url-protocols: 0
  no-vendor-prefixes: 2
  no-warn: 2
  property-units: 0
  indentation: 2

  final-newline: 2
